language: elixir

elixir:
  - 1.9

otp_release:
  - 22.0.7

sudo: false

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - mix check
  - MIX_ENV=test mix coveralls.travis
