language: elixir

elixir:
  - 1.9

otp_release:
  - 22.0.7

cache:
  directories:
    - _build
    - deps

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

before_script:
  - mkdir priv
  - travis_wait mix dialyzer --plt

script:
  - mix check
  - MIX_ENV=test mix coveralls.travis
